version: '3.9'
services:
  frontend: 
    build:
      context: ./form/my-app
      dockerfile: Dockerfile
    ports:
    - "8000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
    